name: tourists
description: Tourists App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

  # Localization Library
  flutter_localizations:
    sdk: flutter

  # DI
  provider: ^4.1.3

  # Dependency injection
  inject:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject
      ref: 7c3cbf6

  # State Management Library
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0

  # Shared Prefs
  shared_preferences: ^0.5.7+3

  # Network Agent
  http: ^0.12.1

  # Streams and RX
  rxdart: ^0.24.1

  # ORM, Database SQL
  sqfentity: ^1.3.5+3

  # Firebase Libs
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1

  # Localization
  gen_lang: 0.1.3

  intl: ^0.16.1

dependency_overrides:
  source_gen: 0.9.5
  analyzer: ^0.39.4
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.3
  test: ^1.14.4
  inject_generator:
    git:
      url: https://github.com/google/inject.dart.git
      path: package/inject_generator
      ref: 7c3cbf6

  # Generate Language Files
  lang_table: 0.2.0

flutter:
  uses-material-design: true

  # assets:
  #  - resources/fonts
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flutter_intl:
  enabled: true
